### ISSUE TITLE
Support for off-canvas menus?

### ISSUE THREAD

**Issue by sandermarechal** [florianbelhomme/FlobFoundationBundle#15]
Hi. Would it be possible to add support for rendering a tab-bar and off-canvas menus using KnpMenu?

**Comment by florianbelhomme** [comment]
I'm going to think about this. I will add this in the TODO list.

But it will be difficult to add the main content using menus of KnpMenu.
Maybe it will be an embed template or macros.

Do you have a suggestion ?

**Comment by sandermarechal** [comment]
I have a modified version of your twig menu template that works for the off-canvas menu. It's only slightly different from the main template, so perhaps it can be integrated with the main template?

**Comment by sandermarechal** [comment]
Here is my template: https://gist.github.com/sandermarechal/c47eba91ff675d5a8de9

**Comment by florianbelhomme** [comment]
I see, but it only generate the menu, it doesn't hide the "tab-bar-section" and the needed markup.
How do you add it ?

Maybe we can add a embed twig file that take a "off-canvas" menu in argument and it add all the markup for you. You juste have to fill the bloc for title and main content.

**Comment by sandermarechal** [comment]
> it doesn't add the "tab-bar-section" and the needed markup. How do you add it?

I add it in my template manually. I myself do that for the top-bar too. I don't use that bit from your bundle so I didn't code it in the tab-bar template. But it should be easy to add in a similar manner to your top-bar menu template.

> Maybe we can add a embed twig file that take a "off-canvas" menu in argument and it add all the markup for you. 

That would be ideal :-) You want to be able to use the same menu's in both the top-bar and in the offcanvas tab-bar menu.
