### ISSUE TITLE
Breadcrumb : display basic breadcrumb when the current route not found in the Menu tree

### ISSUE THREAD

**Issue by Worlor** [florianbelhomme/FlobFoundationBundle#22]
Hello,

When you try to generate a breadcrumb on a page that doesn't exist in the menubuilder, the function

    $breadcrumbs = $manipulator->getBreadcrumbsArray($itemFilterIterator->current());

return an exception

Why not just return an empty breadcrumb ?
On Twig/MenuExtension.php l.100

            // Extract the items for the breadcrumb
        $manipulator = new MenuManipulator();
        $current = $itemFilterIterator->current();
        if($current instanceof ItemInterface)
            $breadcrumbs = $manipulator->getBreadcrumbsArray($itemFilterIterator->current());
        else
            $breadcrumbs = $manipulator->getBreadcrumbsArray($menu);

Thanks

**Comment by florianbelhomme** [comment]
Hi,

I'm going to investingate. Can you add your route and your menu ?

If the page is not in the menu, what is the expected result for the display ?
An empty breadcrumb is strange :/

**Comment by Worlor** [comment]
No display ! The itemFilterIterator->current() return null, so the manipulator throw an exception. 

For example, when you generate CRUD with symfony, it create 6 route : 
   
    entity
    entity_new
    entity_create
    entity_edit
    entity_update
    entity_delete

If (like me) you put the breadcrumb in the layout, and don't add pages on the menu, so the breadcrumb will throw an exception. 
That's true, an empty breadcrumb is strange. But I think the itemFilterIterator should return the parent item when it don't find the current matched item.
At least, it can be good to handle the exception.

**Comment by florianbelhomme** [comment]
> That's true, an empty breadcrumb is strange. But I think the itemFilterIterator should
> return the parent item when it don't find the current matched item.

If you have a way to use the matcher with url and return the most relevent (the nearest parent), please, make a PR.

Actually, i suggest to have a breadcrumb with the first item. Can you check the referenced PR ?
