### ISSUE TITLE
The service "fbfb.twig_extension" has a dependency on a non-existent parameter "flob.foundation.template.breadcrumb".

### ISSUE THREAD

**Issue by rjbijl** [florianbelhomme/FlobFoundationBundle#9]
When installing the dev-master version of the FoundationBundle with composer, I get the following error:

```
[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  The service "fbfb.twig_extension" has a dependency on a non-existent parameter "flob.foundation.template.breadcrumb".
```

I fixed it by adding

```
flob.foundation.template.breadcrumb: FlobFoundationBundle:Menu:foundation_breadcrumb.html.twig
```

to your services_menu.yml, but I guess it should have a default value somewhere?

**Comment by Alphanumerix** [comment]
Hello. I had similiar problem with 2.* version since ever, so I'we been using 1.0.5 for a long time, but today I've started new project. I've pull 2.0.1 version, use config from readme.md and voila! It works :) So imho 2.0.1 can be considered as "stable"
